#!/bin/bash
set -e

echo "==> Granting privileges..."

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_OWNER_USER" -d "$POSTGRES_DB" <<-EOSQL
  GRANT CONNECT ON DATABASE ${POSTGRES_DB}
  TO ${POSTGRES_APP_USER};

  \\c ${POSTGRES_DB}

  GRANT USAGE ON SCHEMA public TO ${POSTGRES_APP_USER};

  GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public
  TO ${POSTGRES_APP_USER};

  GRANT USAGE, SELECT
  ON ALL SEQUENCES IN SCHEMA public
  TO ${POSTGRES_APP_USER};

  ALTER DEFAULT PRIVILEGES
  IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLES TO ${POSTGRES_APP_USER};
EOSQL
